FROM startcodex/openldap:2.0.0
LABEL maintainer="Your Name <your@name.com>"

ADD bootstrap /container/service/slapd/assets/config/bootstrap
ADD certs /container/service/slapd/assets/certs
ADD environment /container/environment/01-custom
